#!/bin/bash

# Code modernization script using clang-tidy
# Focus on constexpr, const, and brace initialization improvements

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
BUILD_DIR="$PROJECT_ROOT/build-relwithdebinfo-llvm-clang"
CLANG_TIDY="/opt/homebrew/opt/llvm/bin/clang-tidy"

echo "🔧 Starting code modernization with clang-tidy..."
echo "Project root: $PROJECT_ROOT"
echo "Build directory: $BUILD_DIR"

# Check if clang-tidy is available
if [[ ! -x "$CLANG_TIDY" ]]; then
    echo "❌ Error: clang-tidy not found at $CLANG_TIDY"
    exit 1
fi

# Check if compilation database exists
if [[ ! -f "$BUILD_DIR/compile_commands.json" ]]; then
    echo "❌ Error: Compilation database not found. Please run cmake with -DCMAKE_EXPORT_COMPILE_COMMANDS=ON"
    exit 1
fi

# Find all source files in the project
SOURCE_FILES=$(find "$PROJECT_ROOT/src" -name "*.cpp" -type f)
HEADER_FILES=$(find "$PROJECT_ROOT/include" -name "*.hpp" -type f)

echo "📁 Found $(echo "$SOURCE_FILES" | wc -l) source files and $(echo "$HEADER_FILES" | wc -l) header files"

# Function to run clang-tidy on a file
run_clang_tidy() {
    local file="$1"
    local check="$2"
    local description="$3"
    
    echo "🔍 Checking $file for $description..."
    
    # Run clang-tidy with specific check and suppress system header errors
    "$CLANG_TIDY" "$file" \
        -p "$BUILD_DIR" \
        --checks="$check" \
        --header-filter='(include/json-query/.*\.(h|hpp)|src/json-query/.*\.(h|hpp))$' \
        --format-style=none \
        2>/dev/null || true
}

# Function to apply fixes
apply_fixes() {
    local file="$1"
    local check="$2"
    local description="$3"
    
    echo "🔧 Applying fixes to $file for $description..."
    
    # Apply fixes with clang-tidy
    "$CLANG_TIDY" "$file" \
        -p "$BUILD_DIR" \
        --checks="$check" \
        --header-filter='(include/json-query/.*\.(h|hpp)|src/json-query/.*\.(h|hpp))$' \
        --fix \
        --format-style=none \
        2>/dev/null || true
}

# Phase 1: Apply safe modernization fixes
echo "🚀 Phase 1: Applying safe modernization fixes..."

SAFE_CHECKS=(
    "modernize-use-nullptr:nullptr usage"
    "modernize-use-bool-literals:boolean literals"
    "modernize-redundant-void-arg:redundant void args"
    "modernize-use-equals-default:default constructors/destructors"
    "modernize-use-override:override specifiers"
    "readability-redundant-string-cstr:redundant c_str calls"
    "readability-container-size-empty:container size checks"
    "performance-faster-string-find:string find optimizations"
)

for check_info in "${SAFE_CHECKS[@]}"; do
    check="${check_info%%:*}"
    description="${check_info##*:}"
    
    echo "📋 Processing: $description"
    
    for file in $SOURCE_FILES; do
        apply_fixes "$file" "$check" "$description"
    done
done

# Phase 2: Analyze and report potential const/constexpr opportunities
echo "🔍 Phase 2: Analyzing const/constexpr opportunities..."

ANALYSIS_CHECKS=(
    "readability-make-member-function-const:const member functions"
    "performance-unnecessary-copy-initialization:unnecessary copies"
    "performance-unnecessary-value-param:value parameter optimization"
    "modernize-use-auto:auto usage opportunities"
)

for check_info in "${ANALYSIS_CHECKS[@]}"; do
    check="${check_info%%:*}"
    description="${check_info##*:}"
    
    echo "📋 Analyzing: $description"
    
    for file in $SOURCE_FILES; do
        run_clang_tidy "$file" "$check" "$description" > "/tmp/clang_tidy_${check//[-:]/_}.log" 2>&1
    done
done

# Phase 3: Report findings
echo "📊 Phase 3: Generating modernization report..."

cat > "$PROJECT_ROOT/modernization_report.md" << 'EOF'
# Code Modernization Report

This report was generated by clang-tidy analysis focusing on:
- constexpr opportunities
- const correctness
- Brace initialization
- Modern C++ patterns

## Applied Fixes

### Phase 1: Safe Automatic Fixes
- ✅ nullptr usage modernization
- ✅ Boolean literal modernization
- ✅ Redundant void argument removal
- ✅ Default constructor/destructor usage
- ✅ Override specifier additions
- ✅ Redundant c_str() call removal
- ✅ Container size check optimizations
- ✅ String find optimizations

## Analysis Results

EOF

# Add analysis results to report
for check_info in "${ANALYSIS_CHECKS[@]}"; do
    check="${check_info%%:*}"
    description="${check_info##*:}"
    log_file="/tmp/clang_tidy_${check//[-:]/_}.log"
    
    if [[ -f "$log_file" ]] && [[ -s "$log_file" ]]; then
        echo "### $description" >> "$PROJECT_ROOT/modernization_report.md"
        echo '```' >> "$PROJECT_ROOT/modernization_report.md"
        head -20 "$log_file" >> "$PROJECT_ROOT/modernization_report.md"
        echo '```' >> "$PROJECT_ROOT/modernization_report.md"
        echo "" >> "$PROJECT_ROOT/modernization_report.md"
    fi
done

echo "✅ Code modernization complete!"
echo "📄 Report saved to: $PROJECT_ROOT/modernization_report.md"
echo ""
echo "🔄 Next steps:"
echo "1. Review the modernization report"
echo "2. Build and test the project to ensure no regressions"
echo "3. Run benchmarks to verify performance is maintained"
echo "4. Consider manual review of const/constexpr opportunities"
