name: "Test Report"

on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  report:
    name: Publish test reports
    # Only report on successful ci runs; a failed run may not have uploaded
    # its test-result artifacts and would just add a second red X.
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Must mirror the build-and-test matrix in ci.yml
        # (artifact: test-results-<os>-<compiler>).
        include:
          - os: ubuntu-latest
            compiler: default
          - os: ubuntu-latest
            compiler: clang
          - os: macos-latest
            compiler: default
          - os: windows-latest
            compiler: default

    steps:
      - uses: dorny/test-reporter@v3
        with:
          artifact: test-results-${{ matrix.os }}-${{ matrix.compiler }}
          name: Test Report (${{ matrix.os }}, ${{ matrix.compiler }})
          path: "*.xml"
          reporter: java-junit
