name: "Test Report"

on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  report:
    name: Publish test report
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v2
        with:
          artifact: test-*     # uploaded by CI workflow
          name: GoogleTest Suite       # name of the check run
          path: "*.xml"                # look for any .xml (JUnit) inside the artifact
          reporter: java-junit         # parse JUnit XML format
