name: "Test Report"

on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  report:
    name: Publish test reports
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: dorny/test-reporter@v2
        with:
          artifact: test-results-${{ matrix.os }}
          name: Test Report (${{ matrix.os }})
          path: "*.xml"
          reporter: java-junit
